#!/usr/bin/env python3
"""Build the PsikiQ site.

  index.html, pricing.html   the ONE source for each page (standalone, previewable)
  partials/header.html       the site header, injected into every page between
                             <!-- HEADER:start --> … <!-- HEADER:end --> (in place)
  ghl/psikiq-*-ghl.html      what gets pasted into each GHL page's single Custom Code
                             element (full-width section)

The GHL output strips the document wrapper, lifts GHL's 1170px row cap on the section
that holds the page, points assets at the public host, and rewrites page links to the
GHL paths.  Run after every change; never hand-edit the ghl/ output.
"""
import re, pathlib
here = pathlib.Path(__file__).parent
IMG_HOST = 'https://nexus-mkii.github.io/psikiq/'
PAGES = {                      # source file -> (GHL output, GHL path, header readout)
    'index.html':   ('ghl/psikiq-home-ghl.html',    '/',        '<span class="w">//</span>&nbsp;<span id="rd">SUPERPOSITION</span>'),
    'pricing.html': ('ghl/psikiq-pricing-ghl.html', '/psikiq-pricing', '<span class="w">//</span>&nbsp;PRICING'),
    'contact.html': ('ghl/psikiq-contact-ghl.html', '/psikiq-contact', '<span class="w">//</span>&nbsp;LISTENING'),
}
# GHL page paths as they exist in the site (the home page is the domain root)
LINKS = {'index.html': '/', 'pricing.html': '/psikiq-pricing', 'contact.html': '/psikiq-contact'}

def relink(text):
    """source pages link to each other as files; the GHL site uses paths. Applies to
    href="…" in markup AND to the same strings inside scripts (CTAs are set at runtime)."""
    for page, gpath in LINKS.items():
        text = (text.replace(f'"{page}#', f'"{gpath}#').replace(f'"{page}"', f'"{gpath}"')
                    .replace(f"'{page}#", f"'{gpath}#").replace(f"'{page}'", f"'{gpath}'"))
    return text

header = (here / 'partials/header.html').read_text()
MARK = re.compile(r'(<!-- HEADER:start[^\n]*-->\n).*?(<!-- HEADER:end -->)', re.S)

GHL_HEAD = '''<!-- PsikiQ {name} — ONE Custom Code element, full-width section. -->
<!-- GENERATED by build_ghl.py from {src} — edit the source, not this file. -->
<style>
  /* GHL caps every section's inner row at 1170px, even "full width" ones.
     Lift it — and the row/column padding — only on the section holding this page. */
  .c-section:has(.hdr) > .inner{{max-width:none!important;width:100%!important;}}
  .c-section:has(.hdr),
  .c-section:has(.hdr) .c-row,
  .c-section:has(.hdr) .c-column{{padding:0!important;margin:0!important;}}
  body{{background:#17110A!important;}}
</style>
'''

for src, (out, path, readout) in PAGES.items():
    p = here / src
    s = p.read_text()
    # 1) refresh the header in place so the source page is always complete on its own
    hdr = header.replace('{{READOUT}}', readout)
    s2, n = MARK.subn(lambda m: m.group(1) + hdr + '\n' + m.group(2), s)
    assert n == 1, f'{src}: header markers missing'
    if s2 != s:
        p.write_text(s2)
    s = s2
    # 2) GHL page: head styles + body, assets on the public host, links to GHL paths
    head_style = re.search(r'(<!-- FONTS.*?</style>)\s*</head>', s, re.S).group(1)
    body = re.search(r'<body>\n(.*)</body>', s, re.S).group(1)
    ghl = head_style + '\n' + body
    ghl = re.sub(r'(psi-[a-z0-9-]+\.webp|icons/[a-z0-9-]+\.(?:png|ico))', lambda m: IMG_HOST + m.group(1), ghl)
    ghl = relink(ghl)
    o = here / out
    o.write_text(GHL_HEAD.format(name=src.replace('.html', ''), src=src) + ghl)
    print(f'{out}: {len(ghl)//1024} KB')

# 3) the header on its own — for any GHL page built in GHL's own editor. Needs the site tokens
#    and fonts, which those pages don't have, so it carries its own.
FONTS = ('https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600'
         '&family=Chakra+Petch:wght@300;400&family=JetBrains+Mono:wght@500&display=swap')
hdr = header.replace('{{READOUT}}', '<span class="w">//</span>&nbsp;PSIKIQ')
hdr = re.sub(r'(psi-[a-z0-9-]+\.webp|icons/[a-z0-9-]+\.(?:png|ico))', lambda m: IMG_HOST + m.group(1), hdr)
hdr = relink(hdr)
standalone = f'''<!-- PsikiQ HUD header — standalone. Paste into a Custom Code element at the TOP of any GHL
     page that is NOT one of the generated psikiq-*-ghl.html pages (those carry it already).
     GENERATED by build_ghl.py from partials/header.html. -->
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="{FONTS}">
<style>
  :root{{--void:#17110A;--white:#FFFFFF;--gold:#E6BE6A;--silver:#C9CFD6;--silver-2:#9AA3AD;--warm:#E8912E;--ink:#17110A;}}
  .mono{{font-family:'JetBrains Mono',ui-monospace,monospace;letter-spacing:0;}}
</style>
{hdr}'''
(here / 'ghl/psikiq-header-ghl.html').write_text(standalone)
print(f'ghl/psikiq-header-ghl.html: {len(standalone)//1024} KB')
