#!/usr/bin/env python3
"""Build the PsikiQ site.

  index.html, pricing.html   the ONE source for each page (standalone, previewable)
  partials/header.html       the site header, injected into every page between
                             <!-- HEADER:start --> … <!-- HEADER:end --> (in place)
  ghl/psikiq-*-ghl.html      what gets pasted into each GHL page's single Custom Code
                             element (full-width section)

The GHL output strips the document wrapper, lifts GHL's 1170px row cap on the section
that holds the page, points assets at the public host, and rewrites page links to the
GHL paths.  Run after every change; never hand-edit the ghl/ output.
"""
import re, pathlib
here = pathlib.Path(__file__).parent
IMG_HOST = 'https://nexus-mkii.github.io/psikiq/'
PAGES = {                      # source file -> (GHL output, GHL path, header readout)
    'index.html':   ('ghl/psikiq-home-ghl.html',    '/',        '<span class="w">//</span>&nbsp;<span id="rd">SUPERPOSITION</span>'),
    'pricing.html': ('ghl/psikiq-pricing-ghl.html', '/pricing', '<span class="w">//</span>&nbsp;PRICING'),
}
LINKS = {'index.html': '/', 'pricing.html': '/pricing'}

header = (here / 'partials/header.html').read_text()
MARK = re.compile(r'(<!-- HEADER:start[^\n]*-->\n).*?(<!-- HEADER:end -->)', re.S)

GHL_HEAD = '''<!-- PsikiQ {name} — ONE Custom Code element, full-width section. -->
<!-- GENERATED by build_ghl.py from {src} — edit the source, not this file. -->
<style>
  /* GHL caps every section's inner row at 1170px, even "full width" ones.
     Lift it — and the row/column padding — only on the section holding this page. */
  .c-section:has(.hdr) > .inner{{max-width:none!important;width:100%!important;}}
  .c-section:has(.hdr),
  .c-section:has(.hdr) .c-row,
  .c-section:has(.hdr) .c-column{{padding:0!important;margin:0!important;}}
  body{{background:#17110A!important;}}
</style>
'''

for src, (out, path, readout) in PAGES.items():
    p = here / src
    s = p.read_text()
    # 1) refresh the header in place so the source page is always complete on its own
    hdr = header.replace('{{READOUT}}', readout)
    s2, n = MARK.subn(lambda m: m.group(1) + hdr + '\n' + m.group(2), s)
    assert n == 1, f'{src}: header markers missing'
    if s2 != s:
        p.write_text(s2)
    s = s2
    # 2) GHL page: head styles + body, assets on the public host, links to GHL paths
    head_style = re.search(r'(<!-- FONTS.*?</style>)\s*</head>', s, re.S).group(1)
    body = re.search(r'<body>\n(.*)</body>', s, re.S).group(1)
    ghl = head_style + '\n' + body
    ghl = re.sub(r'(psi-[a-z0-9-]+\.webp)', lambda m: IMG_HOST + m.group(1), ghl)
    for page, gpath in LINKS.items():
        ghl = ghl.replace(f'href="{page}#', f'href="{gpath}#').replace(f'href="{page}"', f'href="{gpath}"')
    o = here / out
    o.write_text(GHL_HEAD.format(name=src.replace('.html', ''), src=src) + ghl)
    print(f'{out}: {len(ghl)//1024} KB')
