#!/usr/bin/env python3
"""Emit ghl/psikiq-home-ghl.html from index.html.

index.html is the ONE source. The GHL page is one Custom Code element in a
full-width section; this strips the document wrapper, lifts GHL's 1170px row
cap on the section that holds the page, and points the two psi images at their
public host. Run after every change to index.html, then paste the output into
the GHL element.  No other edits belong in the output file.
"""
import re, pathlib
here = pathlib.Path(__file__).parent
src = (here / 'index.html').read_text()
IMG_HOST = 'https://nexus-mkii.github.io/psikiq/'
FONTS = ('https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700'
         '&family=Michroma&family=Chakra+Petch:wght@300;400;500&family=JetBrains+Mono:wght@400;500&display=swap')

# 1) head <style> … </style>  (everything between the first <style> and </head>)
head_style = re.search(r'(<style>.*?</style>)\s*</head>', src, re.S).group(1)
# 2) body contents
body = re.search(r'<body>\n(.*)</body>', src, re.S).group(1)
# psi images live on the public host — GHL has no relative asset path
body = re.sub(r'src="(psi-[a-z]+\.webp)"', lambda m: f'src="{IMG_HOST}{m.group(1)}"', body)

out = f'''<!-- PsikiQ home — ONE Custom Code element, full-width section. -->
<!-- GENERATED by build_ghl.py from index.html — edit index.html, not this file. -->
<style>
  /* GHL caps every section's inner row at 1170px, even "full width" ones.
     Lift it — and the row/column padding — only on the section holding this page. */
  .c-section:has(.hero) > .inner{{max-width:none!important;width:100%!important;}}
  .c-section:has(.hero),
  .c-section:has(.hero) .c-row,
  .c-section:has(.hero) .c-column{{padding:0!important;margin:0!important;}}
  body{{background:#17110A!important;}}
</style>
<link rel="stylesheet" href="{FONTS}">
{head_style}
{body}'''
dst = here / 'ghl' / 'psikiq-home-ghl.html'
dst.write_text(out)
print(f'{dst.relative_to(here)}: {len(out)//1024} KB')
